config/routes.rb
Rails.application.routes.draw do
  # 利用者用ルーティング
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions",
  }

  root to: "user/homes#top"
  get "about" => "user/homes#about", as: "about"

  get 'users' => 'user/users#dummy'

  devise_scope :user do
    post 'user/guest_sign_in', to: 'user/guests#guest_sign_in'
  end

  scope module: :user do
    resources :reviews do
      resources :comments, only: [:create, :destroy]
      resources :reports, only: [:create, :destroy]
    end
    get "ranking" => "reviews#ranking", as: "reviews_ranking"
    resources :users, only: [:edit, :update, :show]
  end

  # 管理者用ルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    root to: "homes#top"
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    get "reports" => "reports#index", as: "reports_index"
    resources :users, only: [:index, :show, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  attachment :profile_image

  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true, length: { maximum: 10 } # 10文字以下

  def self.guest # ゲストログインのメソッド
    find_or_create_by!(email: 'guest@guest.com', name: 'ゲストユーザー') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_signed_in_or_root

  def index
    @users = User.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end

  private

  def admin_signed_in_or_root
    unless admin_signed_in?
      # 管理者ログインしていない場合はtopページに行く
      redirect_to root_path
    end
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :user_or_admin?, only: [:destroy]

  def create
    review = Review.find(params[:review_id])
    comment = current_user.comments.new(comment_params)
    comment.review_id = review.id
    if comment.save
      @review = review
      #バリデーションに引っかかった場合
    else
      @review = review
      @comments = Comment.new
      @report = Report.new
      render 'user/reviews/show'
    end
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    @review = Review.find(params[:review_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  def user_or_admin?
    if !user_signed_in? && !admin_signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/guests_controller.rb
class User::GuestsController < ApplicationController
  # ゲストサインイン
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to reviews_path
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # 新規登録時、ユーザーネームも一緒に登録できるようにする。
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # 新規登録後、レビュー一覧ページに遷移。
  def after_sign_up_path_for(resource)
    reviews_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/reports_controller.rb
class User::ReportsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :user_or_admin?, only: [:destroy]

  def create
    review = Review.find(params[:review_id])
    report = current_user.reports.new(report_params)
    report.review_id = review.id
    report.save
    redirect_to review_path(params[:review_id])
  end

  def destroy
    Report.find_by(id: params[:id]).destroy
    redirect_to review_path(params[:review_id])
  end

  private

  def report_params
    params.require(:report).permit(:report_text)
  end

  def user_or_admin?
    # ユーザーもしくは管理者でログインしているか？
    if !user_signed_in? && !admin_signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy, :ranking]
  before_action :user_or_admin?, only: [:destroy]
  def new
    @review = Review.new
    @genres = Genre.all
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to reviews_path
    else
      @genres = Genre.all
      render :new
    end
  end

  def index
    @genres = Genre.all
    # ↓ジャンルの名前リンクから飛んできた場合
    if params[:genre_id]
      genre = Genre.find(params[:genre_id])
      @reviews = Review.where(genre_id: genre.id).page(params[:page]).per(4).order(created_at: :desc)
    # ↓検索窓に文言を入力してきた場合
    elsif params[:keyword]
      # 検索窓で入力された値をkeywordに代入
      keyword = params[:keyword]
      @reviews = Review.search(keyword).page(params[:page]).per(4)
    # ↓タグのリンクから飛んできた場合
    elsif params[:tag_name]
      @reviews = Review.tagged_with("#{params[:tag_name]}").page(params[:page]).per(4)
    else
      @reviews = Review.page(params[:page]).per(4).order(created_at: :desc)
    end
  end

  def ranking
    @genres = Genre.all
    if params[:ranking_evaluation]
      # 評価高い順にデータ取得
      @reviews = Review.page(params[:page]).per(15).order(evaluation: :desc)
    elsif params[:ranking_view]
      # 閲覧数が多い順にデータ取得
      @reviews = Review.page(params[:page]).per(15).order(impressions_count: :desc)
    else
      redirect_to reviews_path
    end
  end

  def show
    @review = Review.find(params[:id])
    impressionist(@review, nil, unique: [:ip_address]) # IPアドレスで閲覧数カウント
    @comment = Comment.new
    @report = Report.new
  end

  def edit
    @review = Review.find(params[:id])
    @genres = Genre.all
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to reviews_path
    else
      @genres = Genre.all
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:user_id, :genre_id, :title, :image, :good_point, :bad_point, :evaluation, :tag_list)
  end

  # ユーザーサインインもしくは管理者にサインインしてなければトップページに
  def user_or_admin?
    if !user_signed_in? && !admin_signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # ログイン後、トップページに遷移。
  def after_sign_in_path_for(resource)
    reviews_path
  end

  # ログアウト後、トップページに遷移
  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  # サインアップ画面のエラー回避の為のアクションです。
  def dummy
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    # ユーザーネームが”ゲストユーザー”の場合、ユーザー詳細ページに飛ぶ
    if @user.name == "ゲストユーザー"
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/guests_helper.rb
module User::GuestsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/reports_helper.rb
module User::ReportsHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/user/reviews/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <%= link_to reviews_path(tag_name: tag), class: "badge badge-primary mr-1 p-2" do %>
    <%= tag %>
  <% end %>
<% end %>

app/views/user/reviews/index.html.erb
<div class="container my-5">
  <div class="row mb-5">
    <div class="col-12">
      <div class="d-flex flex-wrap">
        <h3 class="font3 col-md-3 col-sm-5 col-lg-2 mt-3">
          レビュー
        </h3>
        <div class="mx-auto mt-3">
          <%= form_with url: reviews_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, placeholder: "ゲームタイトルで検索", class: "form-control ml-5", autocomplete: 'off', size: "50x50" %>
            <% f.submit %>
          <% end %>
        </div>
        <div class="ml-auto h3 mt-3">
          <% unless admin_signed_in? %>
            <%= link_to new_review_path, class: "text-white btn btn-gradient-radius" do %>
              <i class="fas fa-plus-circle"></i>
              レビュー投稿
              <i class="fas fa-plus-circle"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 col-md-12 mb-5">
      <div class="text-right">
        <%= link_to "☆評価順", reviews_ranking_path(ranking_evaluation: "true")%>
        |
        <%= link_to "閲覧数順", reviews_ranking_path(ranking_view: "true")%>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="d-flex flex-wrap col-md-12 mx-auto">
      <% if @reviews.present? %> <!--検索などの結果に該当するレビューがあるか-->
      <% @reviews.each do |review| %>
        <div class="card ml-3 mb-5 col-md-5 d-block review-card mx-auto">
          <div class="card-img-top">
            <%= link_to review_path(review) do %>
              <%= attachment_image_tag review, :image,  fallback: "no_image.jpg", class: "img-size"%>
            <% end %>
          </div>
          <div class="card-body text-center">
            <h4 class="card-title">
              <%= link_to review.title, review_path(review) %>
            </h4>
            <div class="evaluation" data-score="<%= review.evaluation %>"></div>
            <p class="card-text mt-3">
              <%= link_to review.genre.genre_name, reviews_path(genre_id: review.genre.id) %>
            </p>
            <%= render 'user/reviews/tag_list', tag_list: review.tag_list %>
            <p class="card-text mt-3">
              <i class="fa fa-user"></i>：<%= review.user.name %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4 offset-md-5">
      <%= paginate @reviews %>
    </div>
     <% else %>
      <div class="col-md-12 text-center">
        <h3 class="font3">該当するレビューがありません。</h3>
      </div>
    <% end %>
  </div>

  <div class="row mt-5 border py-3">
    <div class="col-12 mb-5">
      <h3 class="text-center">
        <span class="badge badge-secondary badge-pill">カテゴリ一覧</span>
      </h3>
    </div>
    <div class="col-md-12 col-lg-12 d-flex flex-wrap mb-5">
      <% @genres.each do |genre| %>
        <div class="col-lg-3 col-md-4 col-sm-3 mb-2">
          ・<%= link_to genre.genre_name, reviews_path(genre_id: genre.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--評価の☆マークのJavScript-->
<script>
  $('.evaluation').empty();
  $('.evaluation').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/user/reviews/ranking.html.erb
<div class="container my-5">
  <div class="row mb-5">
    <div class="col-12">
      <div class="d-flex flex-wrap">
        <h3 class="font3 col-md-3 col-sm-5 col-lg-2 mt-3">
          レビュー
        </h3>
        <div class="mx-auto mt-3">
          <%= form_with url: reviews_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, placeholder: "ゲームタイトルで検索", class: "form-control ml-5", autocomplete: 'off', size: "50x50" %>
            <% f.submit %>
          <% end %>
        </div>
        <div class="ml-auto h3 mt-3">
          <% unless admin_signed_in? %>
            <%= link_to new_review_path, class: "text-white btn btn-gradient-radius" do %>
              <i class="fas fa-plus-circle"></i>
              レビュー投稿
              <i class="fas fa-plus-circle"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
    <div class="row">
    <div class="col-lg-12 col-md-12 mb-5">
      <div class="text-right">
        <%= link_to "☆評価順", reviews_ranking_path(ranking_evaluation: "true")%>
        |
        <%= link_to "閲覧数順", reviews_ranking_path(ranking_view: "true")%>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="d-flex flex-wrap col-md-12 mx-auto">
      <% if @reviews.present? %> <!--検索などの結果に該当するレビューがあるか-->
      <% @reviews.each do |review| %>
        <div class="card ml-3 mb-5 col-md-5 d-block review-card mx-auto">
          <div class="card-img-top">
            <%= link_to review_path(review) do %>
              <%= attachment_image_tag review, :image,  fallback: "no_image.jpg", class: "img-size"%>
            <% end %>
          </div>
          <div class="card-body text-center">
            <h4 class="card-title">
              <%= link_to review.title, review_path(review) %>
            </h4>
            <div class="evaluation" data-score="<%= review.evaluation %>"></div>
            <p class="card-text mt-3">
              <%= link_to review.genre.genre_name, reviews_path(genre_id: review.genre.id) %>
            </p>
            <%= render 'user/reviews/tag_list', tag_list: review.tag_list %>
            <p class="pt-3">
              総閲覧回数：<%= review.impressions_count %>回
            </p>
            <p class="card-text mt-3">
              <i class="fa fa-user"></i>：<%= review.user.name %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4 offset-md-5">
      <%= paginate @reviews %>
    </div>
     <% else %>
      <div class="col-md-12 text-center">
        <h3 class="font3">該当するレビューがありません。</h3>
      </div>
    <% end %>
  </div>
  <div class="row mt-5 border py-3">
    <div class="col-12 mb-5">
      <h3 class="text-center">
        <span class="badge badge-secondary badge-pill">カテゴリ一覧</span>
        </h3>
    </div>
    <div class="col-md-12 col-lg-12 d-flex flex-wrap mb-5">
      <% @genres.each do |genre| %>
        <div class="col-lg-3 col-md-4 col-sm-3 mb-2">
          ・<%= link_to genre.genre_name, reviews_path(genre_id: genre.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--評価の☆マークのJavScript-->
<script>
  $('.evaluation').empty();
  $('.evaluation').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/user/reviews/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 mb-5">
      <h1 class="text-center mb-4"><span class="badge badge-secondary font3">レビュー詳細</span></h1>
      <!--画像が添付されていれば表示する-->
      <% unless @review.image_id.nil? %>
        <div class="mx-auto mb-5 col-md-12 col-sm-12">
          <%= attachment_image_tag @review, :image, size: "700x500", class: "d-block mx-auto" %>
        </div>
      <% end %>
      <h2 class="text-center"><strong class="border px-3 box font3"><%= @review.title%></strong></h2>
    </div>
  </div>
  <div class="row mb-5">
    <div class="d-flex flex-wrap align-items-center col-md-12">
      <div class="col-md-5 col-lg-3">
        <h4 class="text-center font3"><i class="fa fa-smile text-warning"></i>良かったところ<i class="fa fa-smile text-warning"></i></h4>
      </div>
      <div class="col-md-7 col-lg-9">
        <p class="ml-5 text-break font3"><%=safe_join(@review.good_point.split("\n"),tag(:br))%></p>
      </div>
    </div>
  </div>
  
  <div class="row my-5">
    <div class=" d-flex flex-wrap align-items-center col-md-12">
      <div class="col-md-5 col-lg-3">
        <h4 class="text-center font3"><i class="fa fa-frown text-primary"></i>残念だったところ<i class="fa fa-frown text-primary"></i></h4>
      </div>
      <div class="col-md-7 col-lg-9">
        <p class="ml-5 text-break font3"><%=safe_join(@review.bad_point.split("\n"),tag(:br))%></p>
      </div>
    </div>
  </div>
  
  <div class="row my-5">
    <div class="text-center col-12 mb-5">
      <h4 class="font3">総合評価</h4>
      <div class="evaluation" data-score="<%= @review.evaluation %>"></div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-12 mb-5 text-center">
      <% if @review.user == current_user %>
        <div class="mb-4">
          <%= link_to "レビューを編集する", edit_review_path(@review), class: "btn btn-success" %>
        </div>
        <div>
          <%= link_to "レビューを削除する", review_path(@review), method: :delete, class: "btn btn-danger", data: { confirm: '本当に削除しますか？'} %>
        </div>
      <% elsif admin_signed_in? %>
        <%= link_to "レビューを削除する", review_path(@review), method: :delete, class: "btn btn-danger", data: { confirm: '本当に削除しますか？'} %>
      <% end %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-12 d-flex flex-wrap">
      <!--コメント機能-->
      <div class="col-md-4 col-lg-4 border py-3">
        <h5 class="font3 mb-4 text-center">コメント</h5>
        <div id="comments-index">
          <%= render 'user/comments/post_comments', review: @review %>
        </div>
        <div class="text-center">
          <% if user_signed_in? %>
              <%= form_with(model:[@review, @comment]) do |f| %>
                <%= f.text_area :comment,placeholder: "コメントをここに", class: "form-control" %>
                <div class="mt-3">
                  <%= f.submit "送信", class: "btn btn-info" %>
                </div>
              <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-2 col-lg-2"></div>
        <!--通報機能-->
        <% if user_signed_in? || admin_signed_in? %>
          <div class="col-lg-6 col-md-6 text-center">
            <% if admin_signed_in? || @review.reported_by?(current_user) %>
            <h2 class="font3 text-danger">通報済み</h2>
              <% @review.reports.each do |report| %>
                <% if report.user == current_user || admin_signed_in? %>

                  <p class="text-break"><span class="text-danger">通報内容</span>：<%= report.report_text %></p>
                  <%= link_to "通報取り消し", review_report_path(report.review, report), method: :delete %>
                <% end %>
              <% end %>
            <% else %>
            <div class="switchdsp ">
              <label for="l-1">
              <span class="clicktxt"><i class="fa fa-exclamation-triangle text-warning"></i>通報する<i class="fa fa-exclamation-triangle text-warning"></i></span>
              </label>
              <input type="checkbox" id="l-1">
              <div class="dsp mt-3">
                <%= form_with(model:[@review, @report], local: true) do |f| %>
                  <%= f.text_area :report_text,placeholder: "通報内容を記載してください。", class: "form-control" %>
                  <div class="mt-3">
                    <button type="submit" class="btn btn-danger">通報する</button>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--評価の☆マークのJavScript-->
<script>
  $('.evaluation').empty();
  $('.evaluation').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>